### ISSUE TITLE
Parou de funcionar

### ISSUE THREAD

**Issue by Sulivan1999** [fagiani/track-sequoia#1]
![sequoia](https://user-images.githubusercontent.com/58372000/194950976-19cb3a62-6d91-4bef-8e1e-e0e7dcdcb98a.png)

Infelizmente parou de funcionar já há algumas semanas. Sempre que tento buscar dados de qualquer código de rastreio a execução é encerrada e recebo erros inesperados, acredito que não esteja sendo possível buscar os dados diretamente na Sequoia.

Seria possível verificar o que pode estar ocorrendo?

**Comment by fagiani** [comment]
@Sulivan1999 obrigado por notar! 

Parece que o local onde o hash inicial estava disponível mudou. Pelo que vi, está disponível agora no link de rastreamento da home deles.

Essa é uma excelente oportunidade inicial de contribuir. Se estiver interessado, eu adicionei no `README` instruções de como montar um ambiente local e posso apoiar em qualquer dúvida que tenha.

Fique à vontade para mandar um PR com as alterações vinculando a esta issue.

Abraço!
